# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 22:23
from __future__ import unicode_literals

from django.db import migrations


def clear_empty_current_questionnaires(apps, schema_editor):
    Project = apps.get_model("organization", "Project")
    Project.objects.filter(
        current_questionnaire='').update(current_questionnaire=None)


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_add_audit_fields'),
    ]

    operations = [
        migrations.RunPython(
            clear_empty_current_questionnaires, migrations.RunPython.noop),
    ]
