# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_clear_empty_current_questionnaires'),
        ('questionnaires', '0024_rm_projects_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='current_questionnaire',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questionnaires.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_questionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.Questionnaire'),
        ),
    ]
