# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0023_add_appearance_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together=set([('id_string', 'version')]),
        ),
        migrations.RemoveField(
            model_name='historicalquestionnaire',
            name='project',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='project',
        ),
    ]
