# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 23:18
from __future__ import unicode_literals

from django.db import migrations


def rm_unattached_questionnaires(apps, schema_editor):
    Questionnaire = apps.get_model("questionnaires", "Questionnaire")
    Questionnaire.objects.filter(project=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0024_rm_projects_fk'),
    ]

    operations = [
        migrations.RunPython(
            rm_unattached_questionnaires, migrations.RunPython.noop),
    ]
